development:
  ACCESS_TOKEN: EAADmKOKj8R4BAL7nB2DNLiX39t1fXVAxdWZC55HZCB0wUXNniTeH8Fpu3w8ANqodY9H3Ci8MA1OLiQN78kkGI9qqzzaZB86Jea8nZCqGZBV8ZAgLPxPLwCFIBen1Mi2YZB0UXeg7Vk4YH8wMxgkM37NzusFRZC20IRoZBzFo4U7bMawZDZD
  APP_SECRET: ca116c0ad7dd16507b7c9914000a21e7
  VERIFY_TOKEN: bot_verify_token
